apiVersion: v1
kind: Service
metadata:
  name: echoheaders-lb-public
  namespace: simple-lb
  labels:
    app: echoheaders

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoheaders
  type: LoadBalancer

